FROM rust:alpine as builder
COPY . /rust-redis-pub-sub-async
WORKDIR /rust-redis-pub-sub-async/src
RUN apk update && apk add musl-dev && cargo build

FROM alpine as app
COPY --from=builder /rust-redis-pub-sub-async/target/debug/rust-redis-pub-sub-async /src/rust-redis-pub-sub-async
WORKDIR /src
CMD ["./rust-redis-pub-sub-async"]