FROM rust:alpine as builder
COPY . /rust-graphql
WORKDIR /rust-graphql/src
RUN apk update && apk add musl-dev && \
    cargo build

FROM alpine:latest as app
COPY --from=builder /rust-graphql/target/debug/rust-graphql /src/rust-graphql
WORKDIR /src
CMD ["./rust-graphql"]
